# This file was generated by GoReleaser. DO NOT EDIT.
cask "rulepack" do
  name "rulepack"
  desc "Compose instruction modules from Git-based rule packs."
  homepage "https://github.com/alexgornovoi/rule-pack"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rulepack"

  on_macos do
    on_intel do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "7f67c9c41fa6c6d8ff16505df0052bf17d83df8779106c311314bd7caf1875a0"
    end
    on_arm do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "8f7e3fa62bb178d8d9168043c6e5ac44a054e9d5e1ab93e732c07cf46acff184"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_linux_amd64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "35420a98add87e3ae9a7630ced3a89960d2527605a527d68ed0c57c36e43580c"
    end
    on_arm do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_linux_arm64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "2357c5dfa70232c14d5d400e7c316f410041b68a724eb8322908e4a6a493b95b"
    end
  end

  # No zap stanza required
end
