# This file was generated by GoReleaser. DO NOT EDIT.
cask "rulepack" do
  name "rulepack"
  desc "Compose instruction modules from Git-based rule packs."
  homepage "https://github.com/alexgornovoi/rule-pack"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rulepack"

  on_macos do
    on_intel do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "cc05c7998fc965c8b479f90bf2ff96afbad51c68790faa6666454feee934a45c"
    end
    on_arm do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "bbd2425db71d9cd00200e50096a6ba26a97eecbee6a1fc021a8499eaaa0f963e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_linux_amd64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "0775925b0960df22d2df7b1d6142ceb5eb9465768276753f968a18d35f030b7b"
    end
    on_arm do
      url "https://github.com/alexgornovoi/rule-pack/releases/download/v#{version}/rulepack_#{version}_linux_arm64.tar.gz",
        verified: "github.com/alexgornovoi/rule-pack"
      sha256 "407384b3ed7a32088c502e558f56166301ee6c54330784d1f4c6bdbae4ca5714"
    end
  end

  # No zap stanza required
end
